name: Build and Deploy Nest.js App to ECS

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  ECR_IMAGE: ${{ vars.ECR_IMAGE }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::379055359520:role/github.awa.oidc
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build and push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/arm64 \
            -t $REGISTRY/$ECR_IMAGE:${{ github.sha }} \
            -t $REGISTRY/$ECR_IMAGE:latest \
            --push .

      # - name: Deploy to ECS
      #   run: |
      #     aws ecs update-service \
      #       --cluster MpcsjNestJSStabilityIntegration \
      #       --service MpcsjStabilityAPI \
      #       --force-new-deployment
